services:
  rabbitmq:
    image: bitnami/rabbitmq:4.0.4
    container_name: rabbitmq_base
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_USERNAME=phamnam2003
      - RABBITMQ_PASSWORD=rabbitmq_password
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
    networks:
      - rabbitmq_network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

networks:
  rabbitmq_network:
volumes:
  rabbitmq_data:
